version: '3.6'

networks:
  database:
    external: false
    name: database

services:
  mysql:
    container_name: mysql
    hostname: mysql
    build:
      context: docker
      dockerfile: mysql/Dockerfile
      args:
        - MYSQL_VERSION=5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - database