version: '3.6'

networks:
  mysql:
    external: false
    name: mysql

services:
  db-seeder:
    image: juanfree/db-seeder:latest
    environment:
      - NUMBER_OF_ROWS=${NUMBER_OF_ROWS}
      - ENGINE_TYPE=${ENGINE_TYPE}
      - NAME_OF_THE_DATABASE=${NAME_OF_THE_DATABASE}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - SEED_TYPE=${SEED_TYPE}
    networks:
      - mysql